### ISSUE TITLE
Undefined constant OCA\OpenAi\AppInfo\Application::MODELS_CACHE_KEY in /var/www/nc_01/nextcloud/apps/integration_openai/lib/Service/OpenAiSettingsService.php:75

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/integration_openai#156]
### Which version of integration_openai are you using?

3.1.2

### Which version of Nextcloud are you using?

30.0.2

### Describe the Bug

intergration_openai 3.1.2 fails to update to 3.2.0.
The following exception is thrown:
An unhandled exception has been thrown:
Error: Undefined constant OCA\OpenAi\AppInfo\Application::MODELS_CACHE_KEY in /var/www/nc_01/nextcloud/apps/integration_openai/lib/Service/OpenAiSettingsService.php:75
Stack trace:
#0 /var/www/nc_01/nextcloud/apps/integration_openai/lib/Service/OpenAiSettingsService.php(442): OCA\OpenAi\Service\OpenAiSettingsService->invalidateModelsCache()
#1 /var/www/nc_01/nextcloud/apps/integration_openai/lib/Migration/Version030104Date20241011192830.php(33): OCA\OpenAi\Service\OpenAiSettingsService->setServiceUrl()
#2 /var/www/nc_01/nextcloud/lib/private/DB/MigrationService.php(520): OCA\OpenAi\Migration\Version030104Date20241011192830->postSchemaChange()
#3 /var/www/nc_01/nextcloud/lib/private/DB/MigrationService.php(395): OC\DB\MigrationService->executeStep()
#4 /var/www/nc_01/nextcloud/lib/private/legacy/OC_App.php(736): OC\DB\MigrationService->migrate()
#5 /var/www/nc_01/nextcloud/lib/private/Installer.php(151): OC_App::updateApp()
#6 /var/www/nc_01/nextcloud/core/Command/App/Update.php(87): OC\Installer->updateAppstoreApp()
#7 /var/www/nc_01/nextcloud/3rdparty/symfony/console/Command/Command.php(326): OC\Core\Command\App\Update->execute()
#8 /var/www/nc_01/nextcloud/3rdparty/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#9 /var/www/nc_01/nextcloud/3rdparty/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#10 /var/www/nc_01/nextcloud/3rdparty/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#11 /var/www/nc_01/nextcloud/lib/private/Console/Application.php(183): Symfony\Component\Console\Application->run()
#12 /var/www/nc_01/nextcloud/console.php(87): OC\Console\Application->run()
#13 /var/www/nc_01/nextcloud/occ(11): require_once('...')
#14 {main}

Luckily an occ upgrade fixes this.

### Expected Behavior

Should cleanly update.

### To Reproduce

Try do update intergration_openai from version 3.1.2 to 3.2.0.

**Comment by julien-nc** [comment]
Thanks for reporting this. It's strange. I think there's nothing wrong in the code. It seems like an outdated `OCA\OpenAi\AppInfo\Application` class is loaded when executing the migration in your context. I updated this app in multiple instances without any issue.

It looks like a Php opcache issue to me.

Has anyone else faced this issue?

**Comment by XueSheng-GIT** [comment]
I also faced this issue yesterday and after doing an occ upgrade and disabling maintenance mode, the instance started to work again. But I indeed got a note about opcache interned strings buffer being to low in the system overview.

**Comment by Aliang-code** [comment]
Same problem, stuck in maintenance mode after upgrade
```
{"reqId":"6u2ojX4tRuYtJ88XcOfQ","level":3,"time":"2024-12-16T15:17:34+00:00","remoteAddr":"192.168.1.5","user":"root","app":"index","method":"GET","url":"/index.php/settings/apps/update/integration_openai","message":"Undefined constant OCA\\OpenAi\\AppInfo\\Application::MODELS_CACHE_KEY in file '/www/wwwroot/nextcloud/apps/integration_openai/lib/Service/OpenAiSettingsService.php' line 75","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0","version":"30.0.1.2","exception":{"Exception":"Exception","Message":"Undefined constant OCA\\OpenAi\\AppInfo\\Application::MODELS_CACHE_KEY in file '/www/wwwroot/nextcloud/apps/integration_openai/lib/Service/OpenAiSettingsService.php' line 75","Code":0,"Trace":[{"file":"/www/wwwroot/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/www/wwwroot/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/www/wwwroot/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/www/wwwroot/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/www/wwwroot/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":146,"Previous":{"Exception":"Error","Message":"Undefined constant OCA\\OpenAi\\AppInfo\\Application::MODELS_CACHE_KEY","Code":0,"Trace":[{"file":"/www/wwwroot/nextcloud/apps/integration_openai/lib/Service/OpenAiSettingsService.php","line":442,"function":"invalidateModelsCache","class":"OCA\\OpenAi\\Service\\OpenAiSettingsService","type":"->"},{"file":"/www/wwwroot/nextcloud/apps/integration_openai/lib/Migration/Version030104Date20241011192830.php","line":33,"function":"setServiceUrl","class":"OCA\\OpenAi\\Service\\OpenAiSettingsService","type":"->"},{"file":"/www/wwwroot/nextcloud/lib/private/DB/MigrationService.php","line":520,"function":"postSchemaChange","class":"OCA\\OpenAi\\Migration\\Version030104Date20241011192830","type":"->"},{"file":"/www/wwwroot/nextcloud/lib/private/DB/MigrationService.php","line":395,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/www/wwwroot/nextcloud/lib/private/legacy/OC_App.php","line":736,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/www/wwwroot/nextcloud/lib/private/Installer.php","line":151,"function":"updateApp","class":"OC_App","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/www/wwwroot/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":574,"function":"updateAppstoreApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/wwwroot/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"updateApp","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/wwwroot/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line
":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/www/wwwroot/nextcloud/lib/private/AppFramework/App.php","line":161,
"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/www/wwwroot/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","
class":"OC\\AppFramework\\App","type":"::"},{"file":"/www/wwwroot/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/
www/wwwroot/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/www/wwwroot/nextcloud/apps/integration_openai/lib/Service/OpenAiSe
ttingsService.php","Line":75},"message":"Undefined constant OCA\\OpenAi\\AppInfo\\Application::MODELS_CACHE_KEY in file '/www/wwwroot/nextcloud/apps/integration_openai/lib/
Service/OpenAiSettingsService.php' line 75","exception":{},"CustomMessage":"Undefined constant OCA\\OpenAi\\AppInfo\\Application::MODELS_CACHE_KEY in file '/www/wwwroot/nex
tcloud/apps/integration_openai/lib/Service/OpenAiSettingsService.php' line 75"}}
```
fix with `sudo -u www php occ upgrade` and `sudo -u www php occ maintenance:mode --off`

**Comment by adripo** [comment]
happening also in `v30.0.6`


> fix with `sudo -u www php occ upgrade` and `sudo -u www php occ maintenance:mode --off`

this workaround solved the startup error.

**Comment by kyteinsky** [comment]
I can't reproduce this issue on a fresh NC 31 with v3.1.2 upgrading to v3.2.0.
The upgrade process can be broken due to some other app too.
Please post the upgrade logs (server logs after the upgrade failure) if this happens again, closing till then.
